from math import pi

SCREEN_WIDTH = 540
SCREEN_HEIGHT = 540

PLAYER_SIZE = 54
PLAYER_SPEED = 12
PLAYER_TORQUE = 0.1
PLAYER_BOUND = 120

SENSOR_LOS_LEN = 210
SENSOR_COUNT = 3
SENSOR_FOV = pi / 6

BIT_SIZE = 27
